# Generated by Django 5.2.6 on 2025-09-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('target_url', models.URLField(help_text='URL the ad links to', max_length=500)),
                ('size', models.CharField(choices=[('300x250', 'Medium Rectangle (300x250)'), ('160x600', 'Wide Skyscraper (160x600)'), ('728x90', 'Leaderboard (728x90)'), ('320x50', 'Mobile Banner (320x50)'), ('custom', 'Custom Size')], default='300x250', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle if the ad is currently active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which ads are displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Show ad only on this category page (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
