# Generated by Django 5.2.6 on 2025-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newslettersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
